window.onload = function () {
    var app = document.getElementById('app');
    var hash = window.location.hash;

    if (hash === '#sobre') {
        app.innerHTML = '<h1>Sobre</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit, nisl id gravida elementum, purus ligula eleifend sapien, fermentum eleifend felis dolor non nulla. Phasellus a consectetur neque, id malesuada ante. Mauris tempus purus sit amet bibendum consectetur. Pellentesque sollicitudin nulla a cursus condimentum. Vestibulum sed ipsum arcu. Praesent non neque purus. Nam id quam rutrum, semper felis id, bibendum dui. Phasellus vulputate magna id neque tempus blandit. Donec id pretium justo, a bibendum nisi. Vestibulum sed tortor lacinia, aliquam erat id, consectetur magna. Vivamus vitae odio vitae ligula venenatis dapibus. Ut dapibus sem a nibh viverra, vitae porta libero auctor. Pellentesque consectetur placerat ex quis tristique. Ut magna odio, pharetra ut vehicula pharetra, mollis et tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque gravida imperdiet odio non auctor. Proin dapibus ex id elementum mollis. In blandit vitae elit iaculis lacinia. Nunc consequat iaculis leo euismod hendrerit. Nam eleifend et mi sit amet mollis. Pellentesque eget metus sodales, molestie ipsum vel, ornare tortor. Duis hendrerit sagittis felis sit amet consectetur. Pellentesque hendrerit orci quis ullamcorper scelerisque. Nunc placerat sed purus vitae dictum. Nunc nec odio sed lectus luctus consequat. Etiam cursus diam sed elit suscipit cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Etiam aliquam bibendum metus ut hendrerit.Nullam vel volutpat erat.Etiam sit amet augue purus.Suspendisse varius id elit in dignissim.Pellentesque eu eros sed arcu luctus rhoncus sit amet a purus.Aliquam erat volutpat. Nam iaculis lobortis tortor eget vehicula.Integer pretium tristique ligula quis lacinia.Morbi ac velit sed nibh imperdiet varius ut vel sapien.Vestibulum rhoncus porttitor lacinia.In sollicitudin nec ligula sit amet aliquet.Nulla eu lacus vitae est lobortis gravida nec vitae justo.Quisque aliquam urna sed lobortis vulputate.Morbi maximus quis velit eget laoreet.Pellentesque aliquet justo nisi, ac accumsan mauris porta in.Aliquam non eros ac tellus lacinia lacinia.Suspendisse efficitur urna massa, eget vulputate neque imperdiet non.Praesent rhoncus eros sed velit malesuada congue.Mauris convallis hendrerit sem ornare fermentum.</p > ';
    } else if (hash === '#contato'){
            app.innerHTML = '<h1>Contato</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit, nisl id gravida elementum, purus ligula eleifend sapien, fermentum eleifend felis dolor non nulla. Phasellus a consectetur neque, id malesuada ante. Mauris tempus purus sit amet bibendum consectetur. Pellentesque sollicitudin nulla a cursus condimentum. Vestibulum sed ipsum arcu. Praesent non neque purus. Nam id quam rutrum, semper felis id, bibendum dui. Phasellus vulputate magna id neque tempus blandit. Donec id pretium justo, a bibendum nisi. Vestibulum sed tortor lacinia, aliquam erat id, consectetur magna. Vivamus vitae odio vitae ligula venenatis dapibus. Ut dapibus sem a nibh viverra, vitae porta libero auctor. Pellentesque consectetur placerat ex quis tristique. Ut magna odio, pharetra ut vehicula pharetra, mollis et tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque gravida imperdiet odio non auctor. Proin dapibus ex id elementum mollis. In blandit vitae elit iaculis lacinia. Nunc consequat iaculis leo euismod hendrerit. Nam eleifend et mi sit amet mollis. Pellentesque eget metus sodales, molestie ipsum vel, ornare tortor. Duis hendrerit sagittis felis sit amet consectetur. Pellentesque hendrerit orci quis ullamcorper scelerisque. Nunc placerat sed purus vitae dictum. Nunc nec odio sed lectus luctus consequat. Etiam cursus diam sed elit suscipit cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Etiam aliquam bibendum metus ut hendrerit.Nullam vel volutpat erat.Etiam sit amet augue purus.Suspendisse varius id elit in dignissim.Pellentesque eu eros sed arcu luctus rhoncus sit amet a purus.Aliquam erat volutpat. Nam iaculis lobortis tortor eget vehicula.Integer pretium tristique ligula quis lacinia.Morbi ac velit sed nibh imperdiet varius ut vel sapien.Vestibulum rhoncus porttitor lacinia.In sollicitudin nec ligula sit amet aliquet.Nulla eu lacus vitae est lobortis gravida nec vitae justo.Quisque aliquam urna sed lobortis vulputate.Morbi maximus quis velit eget laoreet.Pellentesque aliquet justo nisi, ac accumsan mauris porta in.Aliquam non eros ac tellus lacinia lacinia.Suspendisse efficitur urna massa, eget vulputate neque imperdiet non.Praesent rhoncus eros sed velit malesuada congue.Mauris convallis hendrerit sem ornare fermentum.</p > ';
    }else {
        app.innerHTML = '<h1>Bem-vindo</h1><form id="itemForm"> <input type="text" id="itemName" placeholder="Nome do item" required> <input type="number" id="itemQuantity" placeholder="Quantidade" required> <button type="submit">Adicionar</button> </form> <ul id="itemList"></ul>';
};

window.onhashchange = function () {
    var app = document.getElementById('app');
    var hash = window.location.hash;

    if (hash === '#sobre') {
        app.innerHTML = '<h1>Sobre</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit, nisl id gravida elementum, purus ligula eleifend sapien, fermentum eleifend felis dolor non nulla. Phasellus a consectetur neque, id malesuada ante. Mauris tempus purus sit amet bibendum consectetur. Pellentesque sollicitudin nulla a cursus condimentum. Vestibulum sed ipsum arcu. Praesent non neque purus. Nam id quam rutrum, semper felis id, bibendum dui. Phasellus vulputate magna id neque tempus blandit. Donec id pretium justo, a bibendum nisi. Vestibulum sed tortor lacinia, aliquam erat id, consectetur magna. Vivamus vitae odio vitae ligula venenatis dapibus. Ut dapibus sem a nibh viverra, vitae porta libero auctor. Pellentesque consectetur placerat ex quis tristique. Ut magna odio, pharetra ut vehicula pharetra, mollis et tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque gravida imperdiet odio non auctor. Proin dapibus ex id elementum mollis. In blandit vitae elit iaculis lacinia. Nunc consequat iaculis leo euismod hendrerit. Nam eleifend et mi sit amet mollis. Pellentesque eget metus sodales, molestie ipsum vel, ornare tortor. Duis hendrerit sagittis felis sit amet consectetur. Pellentesque hendrerit orci quis ullamcorper scelerisque. Nunc placerat sed purus vitae dictum. Nunc nec odio sed lectus luctus consequat. Etiam cursus diam sed elit suscipit cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Etiam aliquam bibendum metus ut hendrerit.Nullam vel volutpat erat.Etiam sit amet augue purus.Suspendisse varius id elit in dignissim.Pellentesque eu eros sed arcu luctus rhoncus sit amet a purus.Aliquam erat volutpat. Nam iaculis lobortis tortor eget vehicula.Integer pretium tristique ligula quis lacinia.Morbi ac velit sed nibh imperdiet varius ut vel sapien.Vestibulum rhoncus porttitor lacinia.In sollicitudin nec ligula sit amet aliquet.Nulla eu lacus vitae est lobortis gravida nec vitae justo.Quisque aliquam urna sed lobortis vulputate.Morbi maximus quis velit eget laoreet.Pellentesque aliquet justo nisi, ac accumsan mauris porta in.Aliquam non eros ac tellus lacinia lacinia.Suspendisse efficitur urna massa, eget vulputate neque imperdiet non.Praesent rhoncus eros sed velit malesuada congue.Mauris convallis hendrerit sem ornare fermentum.</p > ';
    } else if (hash === '#contato') {
        app.innerHTML = '<h1>Contato</h1><p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque hendrerit, nisl id gravida elementum, purus ligula eleifend sapien, fermentum eleifend felis dolor non nulla. Phasellus a consectetur neque, id malesuada ante. Mauris tempus purus sit amet bibendum consectetur. Pellentesque sollicitudin nulla a cursus condimentum. Vestibulum sed ipsum arcu. Praesent non neque purus. Nam id quam rutrum, semper felis id, bibendum dui. Phasellus vulputate magna id neque tempus blandit. Donec id pretium justo, a bibendum nisi. Vestibulum sed tortor lacinia, aliquam erat id, consectetur magna. Vivamus vitae odio vitae ligula venenatis dapibus. Ut dapibus sem a nibh viverra, vitae porta libero auctor. Pellentesque consectetur placerat ex quis tristique. Ut magna odio, pharetra ut vehicula pharetra, mollis et tortor. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Pellentesque gravida imperdiet odio non auctor. Proin dapibus ex id elementum mollis. In blandit vitae elit iaculis lacinia. Nunc consequat iaculis leo euismod hendrerit. Nam eleifend et mi sit amet mollis. Pellentesque eget metus sodales, molestie ipsum vel, ornare tortor. Duis hendrerit sagittis felis sit amet consectetur. Pellentesque hendrerit orci quis ullamcorper scelerisque. Nunc placerat sed purus vitae dictum. Nunc nec odio sed lectus luctus consequat. Etiam cursus diam sed elit suscipit cursus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.Etiam aliquam bibendum metus ut hendrerit.Nullam vel volutpat erat.Etiam sit amet augue purus.Suspendisse varius id elit in dignissim.Pellentesque eu eros sed arcu luctus rhoncus sit amet a purus.Aliquam erat volutpat. Nam iaculis lobortis tortor eget vehicula.Integer pretium tristique ligula quis lacinia.Morbi ac velit sed nibh imperdiet varius ut vel sapien.Vestibulum rhoncus porttitor lacinia.In sollicitudin nec ligula sit amet aliquet.Nulla eu lacus vitae est lobortis gravida nec vitae justo.Quisque aliquam urna sed lobortis vulputate.Morbi maximus quis velit eget laoreet.Pellentesque aliquet justo nisi, ac accumsan mauris porta in.Aliquam non eros ac tellus lacinia lacinia.Suspendisse efficitur urna massa, eget vulputate neque imperdiet non.Praesent rhoncus eros sed velit malesuada congue.Mauris convallis hendrerit sem ornare fermentum.</p > ';
    } else {
        app.innerHTML = '<h1>Bem-vindo</h1><form id="itemForm"> <input type="text" id="itemName" placeholder="Nome do item" required> <input type="number" id="itemQuantity" placeholder="Quantidade" required> <button type="submit">Adicionar</button> </form> <ul id="itemList"></ul>';
    };
}
}